services:
  # Backend API
  - type: web
    name: tour-booking-api
    env: dotnet
    buildCommand: cd TourBookingAPI/TourBookingAPI && dotnet publish -c Release -o out
    startCommand: cd TourBookingAPI/TourBookingAPI/out && dotnet TourBookingAPI.dll --urls=http://0.0.0.0:$PORT
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: tour-booking-db
          property: connectionString

  # Frontend
  - type: web
    name: tour-booking-frontend
    env: node
    buildCommand: cd tour-booking-frontend && npm install && npm run build
    startCommand: cd tour-booking-frontend && npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://tour-booking-api.onrender.com

databases:
  - name: tour-booking-db
    databaseName: tour_booking
    user: tour_user
